CREATE TABLE IF NOT EXISTS CIUDAD_ENTREGA (
    ID_CIUDAD INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INTEGER PRIMARY KEY,
    CEDULA VARCHAR(13) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS ARTICULO (
    ID_ARTICULO NUMERIC(19,0) PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL UNIQUE,
    PRECIO NUMERIC(14,2) NOT NULL CHECK (PRECIO >= 0),
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TIPO_MOVIMIENTO (
    ID_TIPO_MOVIMIENTO NUMERIC(19,0) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    TIPO CHAR(1) NOT NULL CHECK (TIPO IN ('I','E'))
);

CREATE TABLE IF NOT EXISTS COMPROBANTE_CABECERA (
    ID_COMPROBANTE NUMERIC(19,0) PRIMARY KEY,
    NUMERO_COMPROBANTE VARCHAR(50) NOT NULL UNIQUE,
    FECHA TIMESTAMP NOT NULL,
    ID_TIPO_MOVIMIENTO NUMERIC(19,0) NOT NULL REFERENCES TIPO_MOVIMIENTO(ID_TIPO_MOVIMIENTO)
);

CREATE TABLE IF NOT EXISTS COMPROBANTE_DETALLE (
    ID_COMPROBANTE_DET NUMERIC(19,0) PRIMARY KEY,
    ID_COMPROBANTE NUMERIC(19,0) NOT NULL REFERENCES COMPROBANTE_CABECERA(ID_COMPROBANTE) ON DELETE CASCADE,
    ID_ARTICULO NUMERIC(19,0) NOT NULL REFERENCES ARTICULO(ID_ARTICULO),
    CANTIDAD NUMERIC(19,0) NOT NULL CHECK (CANTIDAD > 0),
    PRECIO NUMERIC(14,2) NOT NULL CHECK (PRECIO >= 0)
);

CREATE TABLE IF NOT EXISTS FACTURA_CABECERA (
    ID_FACTURA INTEGER PRIMARY KEY,
    NUMERO_FACTURA VARCHAR(20) NOT NULL UNIQUE,
    FECHA DATE NOT NULL,
    ID_CLIENTE INTEGER NOT NULL REFERENCES CLIENTE(ID_CLIENTE),
    ID_CIUDAD INTEGER NOT NULL REFERENCES CIUDAD_ENTREGA(ID_CIUDAD),
    VALOR_TOTAL NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (VALOR_TOTAL >= 0)
);

CREATE TABLE IF NOT EXISTS FACTURA_DETALLE (
    ID_FACTURA_DET INTEGER PRIMARY KEY,
    ID_FACTURA INTEGER NOT NULL REFERENCES FACTURA_CABECERA(ID_FACTURA) ON DELETE CASCADE,
    ID_ARTICULO INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL CHECK (CANTIDAD > 0),
    PRECIO NUMERIC(14,2) NOT NULL CHECK (PRECIO >= 0)
);

CREATE TABLE IF NOT EXISTS COBRADOR (
    ID_COBRADOR INTEGER PRIMARY KEY,
    CEDULA VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMA_PAGO (
    CODIGO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PAGO_DETALLE (
    ID_PAGO_DET INTEGER PRIMARY KEY,
    FECHA_PAGO DATE NOT NULL,
    VALOR NUMERIC(14,2) NOT NULL CHECK (VALOR > 0),
    CEDULA_COBRADOR INTEGER NOT NULL REFERENCES COBRADOR(ID_COBRADOR),
    CODIGO_FORMA_PAGO INTEGER NOT NULL REFERENCES FORMA_PAGO(CODIGO),
    ID_FACTURA INTEGER NOT NULL REFERENCES FACTURA_CABECERA(ID_FACTURA)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL DEFAULT 'OAUTH',
    ROL VARCHAR(20) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMAIL VARCHAR(150),
    NOMBRE VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS INTEGRACION_HISTORIAL (
    ID_INTEGRACION BIGSERIAL PRIMARY KEY,
    ID_MENSAJE VARCHAR(255) NOT NULL UNIQUE,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    ORIGEN VARCHAR(50) NOT NULL,
    DESTINO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL,
    FECHA_PUBLICACION TIMESTAMP NOT NULL,
    FECHA_PROCESAMIENTO TIMESTAMP NOT NULL,
    INTENTOS INTEGER NOT NULL,
    PAYLOAD_JSON TEXT NOT NULL,
    ID_COMPROBANTE NUMERIC(19,0),
    NUMERO_COMPROBANTE VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS IDX_FACTURA_FECHA ON FACTURA_CABECERA(FECHA);
CREATE INDEX IF NOT EXISTS IDX_PAGO_FACTURA ON PAGO_DETALLE(ID_FACTURA);
CREATE INDEX IF NOT EXISTS IDX_COMPROBANTE_FECHA ON COMPROBANTE_CABECERA(FECHA);
CREATE INDEX IF NOT EXISTS IDX_INTEGRACION_FECHA ON INTEGRACION_HISTORIAL(FECHA_PROCESAMIENTO);

INSERT INTO TIPO_MOVIMIENTO (ID_TIPO_MOVIMIENTO, NOMBRE, TIPO)
VALUES (1, 'Ingreso por compra', 'I')
ON CONFLICT (ID_TIPO_MOVIMIENTO) DO NOTHING;

INSERT INTO TIPO_MOVIMIENTO (ID_TIPO_MOVIMIENTO, NOMBRE, TIPO)
VALUES (2, 'Egreso por venta', 'E')
ON CONFLICT (ID_TIPO_MOVIMIENTO) DO NOTHING;

INSERT INTO FORMA_PAGO (CODIGO, NOMBRE) VALUES (1, 'Efectivo')
ON CONFLICT (CODIGO) DO NOTHING;
INSERT INTO FORMA_PAGO (CODIGO, NOMBRE) VALUES (2, 'Transferencia')
ON CONFLICT (CODIGO) DO NOTHING;
INSERT INTO FORMA_PAGO (CODIGO, NOMBRE) VALUES (3, 'Tarjeta')
ON CONFLICT (CODIGO) DO NOTHING;

INSERT INTO USUARIO (ID_USUARIO, USERNAME, CONTRASENA, ROL, EMAIL, NOMBRE)
VALUES (1, 'admin@nexo.local', 'OAUTH', 'ADMIN', 'admin@nexo.local', 'Administrador')
ON CONFLICT (ID_USUARIO) DO NOTHING;
