services:
  postgresql-0:
    image: bitnamilegacy/postgresql-repmgr:17.6.0-debian-12-r2
  postgresql-1:
    image: bitnamilegacy/postgresql-repmgr:17.6.0-debian-12-r2
  postgresql-2:
    image: bitnamilegacy/postgresql-repmgr:17.6.0-debian-12-r2
  db-lb:
    image: bitnamilegacy/pgpool:4.6.3
